// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: lwruqvdtjflgbvgfuvbn

class SupabaseConfig {
  static const String supabaseUrl = 'https://lwruqvdtjflgbvgfuvbn.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cnVxdmR0amZsZ2J2Z2Z1dmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODgxMjIsImV4cCI6MjA3NTI2NDEyMn0.6S6BwslxsNHubw9-d9XtzEuBfiup9kik8WtpLkSP42Q';
}
